### ISSUE TITLE
CLI Framework

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic-cli#6]
Minimist or https://github.com/dthree/vorpal

**Comment by andrewmallis** [comment]
maybe relevant https://github.com/zurb/foundation-cli

**Comment by RobLoach** [comment]
Very cool, looks like they're using https://www.npmjs.com/package/nopt to parse the CLI options. Brought in nconf to allow configuration options from a config file, or the command line options, or environment variables. Allows a bit more configuration options.
